version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    working_directory: ~/chainx-common-ci

    steps:
      - checkout

      - run:
          name: Setup build environment
          command: |
            apt update
            apt install -y curl wget build-essential zlib1g-dev python libcurl4-openssl-dev libelf-dev libdw-dev cmake binutils-dev libiberty-dev
            curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain none -y;
            source $HOME/.cargo/env
          no_output_timeout: 1800s

      - run:
          name: Format
          command: |
            export PATH=~/.cargo/bin:$PATH
            rustup component add rustfmt
            cargo fmt -- --check

      - run:
          name: Lint
          command: |
            export PATH=~/.cargo/bin:$PATH
            rustup component add clippy
            cargo clippy --all

      - run:
          name: Test
          command: |
            export PATH=~/.cargo/bin:$PATH
            export RUST_BACKTRACE=1
            cd ustd && cargo test && cargo test --no-default-features && cd ..
            cd base58 && cargo test &&  cargo test --no-default-features && cd ..
            cd rlp && cargo test && cargo test --no-default-features && cd ..
            cd primitive-types && cargo test --features 'serde,codec,rlp' && cargo test --no-default-features --features 'codec,rlp' && cd ..
            cd ethereum-types && cargo test --features 'serde,codec,rlp' && cargo test --no-default-features --features 'codec,rlp' && cd ..

      - run:
          name: Coverage
          command: |
            # install kcov
            export KCOV_VERSION=36
            wget https://github.com/SimonKagstrom/kcov/archive/v$KCOV_VERSION.tar.gz
            tar xzf v$KCOV_VERSION.tar.gz && rm v$KCOV_VERSION.tar.gz
            cd kcov-$KCOV_VERSION
            mkdir build && cd build
            cmake .. && make && make install DESTDIR=../../kcov-build
            cd ../.. && rm -rf kcov-$KCOV_VERSION

            # generate and upload code coverage
            for file in $(find target/debug -maxdepth 1 -name '*-*' -a ! -name '*.d' ! -name '.*'); do
              [ -x "${file}" ] || continue
              mkdir -p "target/cov/$(basename $file)"
              ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"
            done
            bash <(curl -s https://codecov.io/bash)
            echo "Uploaded code coverage"

workflows:
  version: 2.1
  build:
    jobs:
      - build
